
#%RAML 1.0
title: Realtimeproject
version: v1
protocols: [HTTP, HTTPS]
uses:
  common: library/sample_library.raml
/enrollment:
  post:
    body:
      application/json:
        type: common.enrollment
        example: !include examples/enrollment_example.json
    responses:
      201:
        body:
          application/json:
            example: "successfully enrollment created"
/course:
  post:
    body:
      application/json:
        type: common.course
        example: !include examples/course_example.json
    responses:
      201:
        body:
          application/json:
            example: "successfully course created"
              
/job:
 post:
   body:
     application/json:
       type: common.job
       example: !include examples/job_example.json
   responses:
     201:
       body:
         application/json:
           example: "successfully job created"
             
   























